### ISSUE TITLE
idea: background image

### ISSUE THREAD

**Issue by malex984** [IMAGINARY/applauncher2#15]
I think it will look cool if one would be able to use some background image instead of the single-color background. 

It should work nicely with application icons since they are required to have a transparent background. 

I would specify that image in a theme file instead of background color. 

What do you think @porst17 ? Or is it already possible to do?

**Comment by elondaits** [comment]
Theme files can already specify a background image through their CSS files. It's possible to do this already.

**Comment by malex984** [comment]
Cool! Then it would be nice to have such an example inside...
