### ISSUE TITLE
Add URL parameters to overwrite/invalidate config options

### ISSUE THREAD

**Issue by porst17** [IMAGINARY/applauncher2#7]
It should be possible to overwrite certain config options like e.g. `lang` such that it is easy to switch the default language even if one has already been specified in `config.yml`.

For `lang`, it would also make sense to be able to invalidate the value supplied in `config.yml` via e.g. `?lang=` such that the default language would be picked up by the system settings (`window.navigator.language`). I can also open a separate issue for this *detect-reasonable-defaults* feature.

Not sure about other URL parameters besides `lang`. That's currently the only one that comes to my mind.

**Comment by elondaits** [comment]
This is already supported for `lang` in the way you describe. The config only specifies the default and available languages. What you cannot do is specify through the query string a language that is not available in the config file.

**Comment by porst17** [comment]
Is it really choosing the system language? I removed `lang` from `config.yml`, but it is still using English instead of German and this is what I can see in the devTools:
```
navigator.language
"de"
IMAGINARY.AppLauncher.lang
"en"
```
Setting `lang: de` in the config properly select German.

**Comment by elondaits** [comment]
No, I don't set or try to meddle with navigator.language ... that's a read-only property that I *could* use as an indicator to decide the language if it's not specified in any other way (which I don't, AFAIR).

But you can use ?lang=<code> when loading appLauncher and override whatever is in config.yml

**Comment by porst17** [comment]
My main use case for this is for applauncher instances hosted online. The default language should be based on the system language of the user. Fixing the language via `?lang=de` is not very helpful for most users outside Germany and I don't want to put a separate `index.html` that checks for `navigator.language` and forwards to the appropriate `applauncher2/index.html?lang=<code>`.

**Comment by elondaits** [comment]
Understood. That's reasonable. But this issue has two separate things, one that is already implemented (URL parameters overriding) and one that isn't (using navigator.language).

**Comment by porst17** [comment]
Separated the default language part into #9 

Since I can't think of other reasonable URL parameters at the moment, I will close this issue.
